### ISSUE TITLE
Compatibility with WPML Wordpress multiple languages

### ISSUE THREAD

**Issue by lammertb** [chiilog/simple-definition-list-blocks#6]
Hi I tried your plugin on a site with multiple languages which are translated through the WPML plugin. Unfortunately the simple definition list blocks do not turn up in the translation editors. The text in the dt and dt blocks is therefore not translated.

According to WPML support it is because the plugin is lacking a wpml-config.xml configuration file https://wpml.org/documentation/support/language-configuration-files/#gutenberg-blocks

Their advise was to ask the plugin author to join their Go Global program. https://wpml.org/documentation/support/go-global-program/

Would you be willing to make your plugin multi-lingual?

Regards, Lammert

**Comment by lammertb** [comment]
I just added a pull request with an XML file for the WPML plugin support. #7

**Comment by chiilog** [comment]
Thank you very much.
I merged it!
